config/routes.rb
Rails.application.routes.draw do
  resources :friends
  get 'home/index'

  devise_for :users
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
    belongs_to :user
    validates_presence_of :first_name, :last_name, :email, :address
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name,:last_name])
  end
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    before_action :authenticate_user!
    def index
        @friends = Friend.where('user_id=?',current_user.id)
    end

    def new
        @friend = Friend.new
    end

    def create
        @friend = Friend.new(friend_params)
        @friend.user_id = current_user.id

        if @friend.save
            redirect_to friends_path, :notice => "New friend #{@friend.first_name} has been saved!"
        else
            render 'new'
        end
    end

    def edit
        @user = User.find(current_user.id)
        @friend = @user.friends.find(params[:id])
    end

    def update
        @user = User.find(current_user.id)
        @friend = @user.friends.find(params[:id])

        if @friend.update_attributes(friend_params)
            redirect_to friends_path, :notice => 'Your friend was updated successfully!'
        else
            render 'edit'
        end
    end

    def show
        @user = User.find(current_user.id)
        @friend = @user.friends.find(params[:id])
    end

    def destroy
        @friend = Friend.find(params[:id])
        if @friend.destroy
            redirect_to friends_path, :notice => 'Your friend was removed successfully'
        end
    end

    private

    def friend_params
        params.require(:friend).permit(:first_name, :last_name, :user_id,:email, :address, :contact)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!
  def index
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<div class="row">
  <div class="col-sm-2 col-sm-offset-4">
    <h2>New Friend!</h2>
  </div>
</div>

<%= form_for @friend, class: 'form-horizontal' do|f| %>
     <div class = "form">
        <div class = "row">
        <div class = "col-sm-2 col-sm-offset-4">
            <%= f.label :first_name do%>
                <span class="required">First Name *</span>
            <% end %>
        </div>
        
        </div>
        <div class = "row">
        <div class = "col-sm-3 col-sm-offset-4">
            <%= f.text_field :first_name, autofocus: true, class: "form-control" %>
        </div>
        <div class="col-sm-3">
          <% if @friend.errors[:first_name].any?  %>
              <span class="error">First Name <%= @friend.errors[:first_name][0] %></span>
            <% end %>
        </div>
        </div>
    </div>

    <div class = "row">
      <div class = "col-sm-2 col-sm-offset-4">
        <%= f.label :last_name do %>
            <span class="required">Last Name *</span>
        <% end %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-3 col-sm-offset-4">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
      <div class="col-sm-3">
          <% if @friend.errors[:last_name].any?  %>
              <span class="error">Last Name <%= @friend.errors[:last_name][0] %></span>
            <% end %>
        </div>
    </div>

    <div class = "row">
      <div class = "col-sm-2 col-sm-offset-4">
        <%= f.label :email do %>
          <span class="required">Email *</span>
        <% end %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-3 col-sm-offset-4">
        <%= f.text_field :email, class: "form-control" %>
      </div>
      <div class="col-sm-3">
          <% if @friend.errors[:email].any?  %>
              <span class="error">Email <%= @friend.errors[:email][0] %></span>
            <% end %>
        </div>
    </div>

    <div class = "row">
      <div class = "col-sm-2 col-sm-offset-4">
        <%= f.label :address do %>
          <span class="required">Address *</span>
        <% end %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-3 col-sm-offset-4">
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="col-sm-3">
          <% if @friend.errors[:address].any?  %>
              <span class="error">Address <%= @friend.errors[:address][0] %></span>
            <% end %>
        </div>
    </div>

    <div class = "row">
      <div class = "col-sm-2 col-sm-offset-4">
        <%= f.label :contact  %>
      </div>
    </div>
    <div class = "row">
      <div class = "col-sm-3 col-sm-offset-4">
        <%= f.text_field :contact, class: "form-control" %>
      </div>
    </div>

    <br/>

    <div class="row">
        <div class = "col-sm-2 col-sm-offset-4">
            <%= f.submit "Save", class: "btn btn-primary" %>
        </div>
    </div>
<% end %>

app/views/friends/edit.html.erb
<%=  render 'form' %>

app/views/friends/index.html.erb
<div class="row">
    <% @friends.each do |f| %>
        <div class="col col-sm-4">
            <div class = "panel panel-primary">
                <div class = "panel-heading">
                    <%= f.first_name + " "+ f.last_name%>

                    <div class="btn-group pull-right ">
                        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action <span class="caret"></span>
                        </button>
                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to('Edit', edit_friend_path(f)) %>
                            </li>
                            <li>
                                <%= link_to('Trash', '/friends/'+f.id.to_s, method: 'delete') %>
                            </li>
                        </ul>
                    </div>
                    
                </div>
                <div class = "panel-body">
                    Address : <%= f.address %> <br/>
                    <% if f.contact? %>
                        Contact : <%= f.contact %> <br/>
                    <% end %>
                    <a class="btn btn-danger" href="#">
                        <i class= "fa fa-envelope"></i>
                        <%= f.email %>
                    </a>
                </div>
            </div>
        </div>
    <% end %>
</div>

app/views/friends/new.html.erb
<%= render 'form' %>

app/views/friends/show.html.erb
<%= @friend.first_name %>

app/views/home/index.html.erb
<h2>Allo ! <%= @user.first_name %> how can I help? </h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FriendsManager</title>
    <%= csrf_meta_tags %>
    <meta name = "viewport" content="width=device-width, initial-sacal=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
  <div class = "container-fluid">
  <nav class="navbar navbar-inverse">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#my-navbar-collapse" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Brand</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="my-navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to('Home', home_index_path) %></li>
      </ul>
      
      <ul class="nav navbar-nav navbar-right">
      <% if user_signed_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" 
                        data-toggle="dropdown" 
                        role="button" aria-haspopup="true" 
                        aria-expanded="false">Explore <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to('Friends', friends_path) %></li>
              <li><%= link_to('Add Friend', new_friend_path) %></li>
            </ul>
          </li>
          <li><%= link_to('Logout',destroy_user_session_path, method: 'delete') %><li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>
  </div>
  <div class="container-fluid">
    <% if flash.any? %>
      <% flash.each do |type, message| %>
         <script>
            toastr.options = {
              "positionClass":"toast-bottom-right"
            }
            toastr.info('<%= message %>');
        </script>
      <% end %>
    <% end %>
    <%= yield %>
  </div>
  </body>
</html>